### ISSUE TITLE
UFAL/PY-Resource Policies - duplicity

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-import#110]
You can see duplicity in the Restricted Collection: `Wikitongues Oral Histories`
![image](https://github.com/dataquest-dev/dspace-python-api/assets/90026355/d71364a6-80d4-442a-9aec-4848c4826597)

It is because in Dspace5 exist only DEFAULT_READ group for action BITSTREAM_DEFAULT_READ nad ITEM_DEFAULT_READ
and for Dspace7 it is devited between ITEM_DEFAULT_READ and BITSTREAM_DEFAULT_READ. So one group from Dspace5 is mapping into two groups in Dspace7. Fix this problem by mapping resource policy with action 9 to group witch name contains BITSTREAM_DEFAULT_READ and not for the both created group.

**Comment by vidiecan** [comment]
@milanmajchrak still valid?
