### ISSUE TITLE
Check the sequence of the table after the import

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-import#159]
**Description:**
Sequences are copied from v5 into v7. Why they are copied? Check the count of the records in the database and compare it with current sequence from v7 with the v5 sequence, if there is difference - why? Do we want to copy it?

PR where the sequences are copied - https://github.com/dataquest-dev/dspace-import/pull/91/commits/b16686b97df49a2994241f81aefee628e5c0011f

PR where copying of some sequences are ignored: https://github.com/dataquest-dev/dspace-import/pull/158

**Comment by vidiecan** [comment]
https://github.com/dataquest-dev/dspace-import/commit/65aaaee4235c1aa3876ea8883d3bbe63c2a1fd27

**Comment by vidiecan** [comment]
check: https://github.com/dataquest-dev/dspace-angular/actions/runs/10093058954/job/27908129738 once it is done
